baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "OrangeFS Documentation"
theme = "docdock"
# themesdir = "../.."
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
googleAnalytics = "UA-"


# [Languages]
# [Languages.en]
# title = "OrangeFS Documentation"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "Documentation du OrangeFS"
# weight = 2
# languageName = "Fran√ßais"




[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = true # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = "false" # set true to open shortcuts links to a new tab/window
enableGitInfo = "true"
anonifyurls = "true"

[outputs]
home = [ "HTML", "RSS", "JSON"]


# [[menu.shortcuts]]
# pre = "<h3>More</h3>"
# name = "<i class='fa fa-github'></i> <label>label</label>"
# identifier = "ds"
# url = "http://orangefs.com"
# weight = 10

# [[menu.shortcuts]]
# name = "<i class='fa fa-cloud-download'></i> <label>Download</label>"
# url = "https://github.com/vjeantet/hugo-theme-docdock/archive/master.zip"
# weight = 11

# [[menu.shortcuts]]
# name = "<i class='fa fa-bookmark'></i> <label>Hugo Documentation</label>"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[menu.shortcuts]]
# name = "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
# url = "/credits"
# weight = 30